advpay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('base.urls')),
    path('payments/', include('payments.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

base/urls.py
from django.urls import path

from base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),

]

payments/urls.py
from django.urls import path

import payments.views
from payments.views import info, send_payment_request

app_name = 'payments'
urlpatterns = [
    path('info/<slug:slug>', info, name='info'),
    path('request/', send_payment_request, name='send_payment_request'),
]

core/models.py
# from django.db import models
# from utils.models import Base
# from django.contrib.auth.models import User
#
#
# class Profile(Base):
#     class Meta:
#         verbose_name = 'perfil'
#         verbose_name_plural = 'perfis'
#
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return "perfil do usuário {}".format(self.user)

payments/models.py
from uuid import uuid4

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.template.defaultfilters import slugify


def only_int(value):
    if value.isdigit() == False:
        raise ValidationError('ID contém caracteres.')


class Company(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    CNPJ = models.CharField(max_length=14, validators=[only_int])

    def __str__(self):
        return self.company_name


class Supplier(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    supplier_name = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    CNPJ = models.CharField(max_length=14, validators=[only_int])

    def __str__(self):
        return self.supplier_name


STATUS_CHOICES = (
    (0, 'unrequested'),
    (1, 'in progress'),
    (2, 'canceled'),
    (3, 'aproved'),
)


class Payment(models.Model):
    payment_id = models.AutoField(primary_key=True, editable=False)
    supplier = models.ForeignKey('Supplier', on_delete=models.PROTECT)
    company = models.ForeignKey('Company', on_delete=models.PROTECT)
    issue_date = models.DateField()
    due_date = models.DateField()
    original_value = models.DecimalField(decimal_places=2, max_digits=14)
    status = models.IntegerField(default=0, choices=STATUS_CHOICES)

    def __str__(self):
        return f'{self.payment_id}'

utils/models.py
#!coding:utf-8
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


class Base(models.Model):
    """Model Base para todos os outros models do projeto."""

    class Meta:
        abstract = True

    created = models.DateTimeField('Criado em', default=timezone.now)
    updated = models.DateTimeField('Alterado em', auto_now=True)

payments/forms.py
from django import forms

from .models import Payment


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = [
            'company',
            'supplier',
            'issue_date',
            'due_date',
            'original_value',
        ]

base/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render


# Create your views here.
@login_required
def home(request):
    user_logged = User.get_username
    return render(request, 'base/home.html', {'user_logged': user_logged})

core/views.py
from django.shortcuts import render

# Create your views here.

payments/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from rolepermissions.checkers import has_object_permission

from payments import facade
from payments.forms import PaymentForm
from payments.models import Company


def send_payment_request(request):
    form = PaymentForm(request.POST or None)
    if form.is_valid():
        form.save()
    return render(request, 'payments/payment_request.html', {'form': form})


def info(request, slug):
    company = Company.objects.get(slug=slug)
    if has_object_permission('company_content', request.user, company):
        return render(request, 'payments/info.html', context={'company': company})
    return render(request, 'base/home.html')

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}AdvPay{% endblock title %}</title>

    <meta name="description" content="{% block description %}Advance Payments. For you.{% endblock description %}">
    <meta name="author" content="Tomás Rajão">

    <link rel="icon" type="image/png" href="{% static 'img/adv.png' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

</head>
<body>
{% block navbar %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">

            <nav class="navbar navbar-light">
                <div class="container-fluid ">
                    <a class="navbar-brand" href="{% url 'base:home' %}">
                        <img src="{% static 'img/adv.png' %}" alt="" width="30%" height="auto">
                    </a>

                    {% if user.is_authenticated %}
                    <div class="nav-item dropdown">
                        <a style="color:#000  !important " class="nav-link dropdown-toggle" href="" id="navbarDropdown"
                           role="button" data-toggle="dropdown"
                           aria-expanded="false">
                            Olá, {{ user.first_name }}
                        </a>
                        <div class=" dropdown-menu" aria-labelledby="navbarDropdown">
                            <div class="dropdown-item">
                                <a class="btn btn-danger" href="{% url 'logout' %}">Sair</a>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <div class="nav-item dropdown">

                                <a class="btn btn-primary" href="{% url 'login' %}">Login</a>

                    </div>
                    {% endif %}


                </div>
            </nav>
        </div>
    </div>
</div>
</nav>
{% endblock navbar %}

{% block body %}
{% endblock body %}
</body>
</html>

base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">

            <div class="jumbotron">
                <h3>

                </h3>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>
</div>
{% endblock body %}

payments/templates/payments/info.html
{% extends 'base/base.html' %}
{% block body%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <table class="table">
                <h3>{{ supplier.company }}</h3>
                <thead>
                <tr>
                    <th scope="col">Supplier</th>
                    <th scope="col">Issue Date</th>
                    <th scope="col">Due date</th>
                    <th scope="col">Original Value</th>
                </tr>
                </thead>
                <tbody>
                {% for supplier in suppliers %}
                <tr>
                    <td>{{ supplier.supplier }}</td>
                    <td>{{ supplier.issue_date }}</td>
                    <td>{{ supplier.due_date }}</td>
                    <td>{{ supplier.original_value }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="col-md-4">
            </div>
        </div>
    </div>
</div>
{% endblock body%}

payments/templates/payments/payment_request.html
{% extends 'base/base.html' %}
{% block body%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <form>
                {{ form.as_p }}
                <input type="submit" value="Save"/>
            </form>
            <div class="col-md-4">
            </div>
        </div>
    </div>
</div>
{% endblock body%}